title: Mittu Shaji
# logo: /assets/img/headshot_circle.png
description: Data & Analytics Engineer | Python, SQL, Power BI, Tableau
url: "https://mittushaji25.github.io"
# show_downloads: true
theme: jekyll-theme-minimal
